### ISSUE TITLE
Black Panther

### ISSUE THREAD

**Issue by nicolo-ribaudo** [dlowe-net/mcu_deps#1]
Hey, I think "Black Panther" _might_ depend on "Captain America: Civil War", since it introduces the character, and it should be a dependency of "The Avengers: Infinity War", since Wakanda has a significant role in the movie (especially at the end). Any reason for the missing links?

Cool project btw! :)

**Comment by dlowe-net** [comment]
I think BP is comprehensible without Civil War, even if the character is established.

You're totally right about Infinity War's dependence on BP, and that's been corrected. Thank you!
